### PR TITLE
Rey 1776/dashboard unit test

### PR DESCRIPTION
**Pull request by rey1776**
added a few test for dashboard.test.tsx

### CODE REVIEW

**Comment by rey1776** [comment]
It looks like it also added my coverage pull. You can ignore that, only real changes are to Dashboard.test.tsx in test folder.

**Comment by rey1776** [comment]
I removed the coverage folder.

**Review by Bryar-Frank — APPROVED** [review]
Low Priority: is only at 70% but otherwise LGTM so I am submitting for merge in case anyone else want to take it on

**Review by MaelstromDef — APPROVED** [review]
LGTM

**Review by jmensah365 — APPROVED** [review]

**Review by Anthowu07 — APPROVED** [review]

**Pull request merged**
