### PR TITLE
Brittshook/refactor frontend

### PR DESCRIPTION
**Pull request by brittshook**
Will refactor tax folder further in another PR

### CODE REVIEW

**Review by d-swe — APPROVED** [review]
Looks good, GJ!

**Review by daniel413x — APPROVED** [review]

**Comment by brittshook** [comment]
Converted to draft to make changes based on new PRs

**Review by d-swe — APPROVED** [review]
Looks good, GJ!

**Comment by brittshook** [comment]
- Moved tax files from pages to appropriate folders
- Moved test setup files to src/test
- Moved tests closer to source code by creating __tests__ sub-folders inside respective folders

**Review by daniel413x — APPROVED** [review]

**Pull request merged**
