### PR TITLE
Refactoring/urls

### PR DESCRIPTION
**Pull request by MaelstromDef**
Short: Went through and refactored all hard coded endpoints to point to a centralized variable that extracts from the environment.

Long:
Created an api folder inside src that holds a base Endpoint.tsx file, which contains the base URL. Inside the api folder is the services folder, which hold files for all services that contain outward-facing API endpoints, and contains each endpoint inside of those services with the naming convention "URL_<Spring method name>", and containing the comment about the method as noted in Spring. All of these URLs use the Endpoint base URL as a base.

After doing this, I rewrote all references to localhost to point to one of the URLs in the api folder.

IMPORTANT NOTE:
On top of touching a lot of files, I could have replaced one of the localhost endpoints with something wrong. This pull is **extremely dangerous** and should be approved after a review from **all** frontend testers.

### CODE REVIEW

**Review by Anthowu07 — APPROVED** [review]

**Review by jmensah365 — APPROVED** [review]

**Review by msabas1 — APPROVED** [review]
Approved, although I am still wondering if some sort of SpendingService.tsx should be included. Might need further clarification regarding this

**Comment by MaelstromDef** [comment]
> Approved, although I am still wondering if some sort of SpendingService.tsx should be included. Might need further clarification regarding this

From what I can tell, the Spending page(s) only use the TransactionService from the backend, and I couldn't find any SpendingService. I believe all Spending page API requests go through transactionsCalculator.ts, please correct me if I'm wrong.

**Comment by msabas1** [comment]
> > Approved, although I am still wondering if some sort of SpendingService.tsx should be included. Might need further clarification regarding this
> 
> From what I can tell, the Spending page(s) only use the TransactionService from the backend, and I couldn't find any SpendingService. I believe all Spending page API requests go through transactionsCalculator.ts, please correct me if I'm wrong.

I just double checked this and Spending.tsx & SpendingMonth.tsx each only have one useEffect where they call getTransactionByUserId() which reside within transactionService.ts

Looks clearer now that transactionService.ts is the only service Spending & SpendingMonth use, LGTM

**Review by Bryar-Frank — APPROVED** [review]
Everything seems to be working correctly now

**Review by Aldrich19 — APPROVED** [review]

**Pull request merged**
